package eapli.base.questionnaire.domain.Question;

public enum Question_Type {

    FREE_TEXT, NUMERIC, SINGLE_CHOICE, SINGLE_CHOICE_WITH_INPUT_VALUE, MULTIPLE_CHOICE, MULTIPLE_CHOICE_WITH_INPUT_VALUE, SORTING_OPTIONS, SCALING_OPTIONS
}
