@startuml
'https://plantuml.com/class-diagram

actor Customer

Customer -> AnswerQuestionnaireUI : asks to answer a questionnaire

activate AnswerQuestionnaireUI
AnswerQuestionnaireUI -> Customer : asks to type the necessary data(id, etc...)

Customer -> AnswerQuestionnaireUI : types the requested data

control CreateAnswerController
AnswerQuestionnaireUI -> CreateAnswerController : create()

activate CreateAnswerController
AnswerQuestionnaireUI -> CreateAnswerController : createNewAnswer(id, etc...)

CreateAnswerController -> PersistenceContext : repositories()

database RepositoryFactory #lightblue
PersistenceContext -> RepositoryFactory : create()

database AnswerRepository #lightblue
RepositoryFactory -> AnswerRepository : create()

CreateAnswerController -> Answer : newAnswer = new Answer(id, etc...)

CreateAnswerController -> AnswerRepository : save(newAnswer)
deactivate CreateAnswerController
@enduml