@startuml
'https://plantuml.com/class-diagram

class CreateReportUI {
+doShow()
}

class CreateReportController {
+createNewReport(questionnaire)
}

class Questionnaire {
+Questionnaire(id, title, etc...)
}

CreateReportUI ..> CreateReportController
CreateReportController ..> Questionnaire
@enduml